exclude: /migrations/
repos:
-   repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
    -   id: black
        entry: black --line-length=79
-   repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        entry: flake8 --extend-ignore=E203
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        entry: isort --profile black --line-length=79
